# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build URCHIN'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["urchin_left","urchin_right"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
